steps:
  # Build the N8N container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/n8n:$COMMIT_SHA', './services/n8n']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/n8n:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'n8n-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/n8n:$COMMIT_SHA'
      - '--region'
      - 'australia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'N8N_HOST=$$N8N_HOST,WEBHOOK_URL=$$WEBHOOK_URL,N8N_EDITOR_BASE_URL=$$N8N_EDITOR_BASE_URL'
      - '--set-secrets'
      - 'DB_HOST=DB_HOST:latest,DB_NAME=DB_NAME:latest,DB_USER=DB_USER:latest,DB_PASSWORD=DB_PASSWORD:latest,N8N_BASIC_AUTH_USER=N8N_BASIC_AUTH_USER:latest,N8N_BASIC_AUTH_PASSWORD=N8N_BASIC_AUTH_PASSWORD:latest'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:australia-southeast1:keyview-db'

images:
  - 'gcr.io/$PROJECT_ID/n8n:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
